version: '3.8'

services:
  web:
    build: .
    ports:
      - "50869:50869"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped