version: '3.8'

services:
  web:
    build: .
    expose:
      - "50869"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ALLOW_ALL_INTERFACES=true
      # (Optional) Provide a comma-separated list of allowed proxy IPs
      # ALLOWED_PROXY_IPS=172.18.0.2,172.18.0.3
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web